channel, remove unused mutex
* The channel is not thread safe, as the mutex has never been
  used.  This simply removes the field.
* Document the lack of thread-safety on channel accessor.
* Found via golangci-lint
  Error: channel.go:89:2: field `mu` is unused (unused)